"""add actual_usage to Material

Revision ID: 7aa6be45f21f
Revises: 
Create Date: 2025-04-07 13:26:55.478787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa6be45f21f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eco_blocks')
    op.add_column('materials', sa.Column('actual_usage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'actual_usage')
    op.create_table('eco_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('carbon_savings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('project_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('used_in_project', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_added', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='eco_blocks_pkey')
    )
    # ### end Alembic commands ###
